# Generated by Django 4.2.6 on 2023-12-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rucprac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='Tag_FK_MTM',
            field=models.ManyToManyField(to='rucprac.product'),
        ),
    ]
