# Generated by Django 4.2.6 on 2023-12-08 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rucprac', '0002_alter_tag_tag_fk_mtm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderposition',
            name='OrderPosition_Order_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='rucprac.order'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='OrderPosition_Product_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderPosition_product_PK', to='rucprac.product'),
        ),
    ]
